### DISCUSSION TITLE
Failed to connect to the browser instance, will retry in 5 secs (via Docker and Ansible)

### DISCUSSION THREAD

**Discussion by Unambiguous** [karakeep-app/karakeep#1087] [Q&A]
### Issue

My instance is also suffering from the problem #674 - Failed to connect to the browser instance, will retry in 5 secs.

I tried both `http://` and `ws://` before the address, but the issue still remains.

The log displays:
```
2025-03-02T07:06:34.111Z info: [Crawler] Connecting to existing browser instance: http://hoarder-chrome:9222
2025-03-02T07:06:34.113Z info: [Crawler] Successfully resolved IP address, new address: http://172.18.0.2:9222/
2025-03-02T07:06:34.115Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs: TypeError: Failed to fetch browser webSocket URL from http://172.18.0.2:9222/json/version: fetch failed
```

### Analysis

When I run `curl` inside the hoarder app container, I get the following output:
```shell
/app # curl http://hoarder-chrome:9222/json/version
curl: (7) Failed to connect to hoarder-chrome port 9222 after 0 ms: Could not connect to server
/app # curl http://172.18.0.2:9222/json/version
curl: (7) Failed to connect to 172.18.0.2 port 9222 after 0 ms: Could not connect to server
```

The chrome container seems to be listening on the port:
```shell
/usr/src/app $ netstat -tlnp | grep 922
tcp        0      0 127.0.0.1:9222          0.0.0.0:*               LISTEN      1/chromium
```

### Configuration

All containers are running on their own Docker network.

My configuration file in Ansible:
```yaml
- name: Docker - create network - hoarder
  docker_network:
    name: hoarder
    driver: bridge

- name: Docker - create container - hoarder / chrome
  docker_container:
    name: hoarder-chrome
    image: gcr.io/zenika-hub/alpine-chrome:123  # zenika/alpine-chrome:124
    state: started
    recreate: yes
    restart_policy: unless-stopped # always
    networks:
      - name: hoarder
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --headless=new

- name: Docker - create container - hoarder / meilisearch
  docker_container:
    name: hoarder-meilisearch
    image: getmeili/meilisearch:v1.11.1
    state: started
    recreate: yes
    restart_policy: unless-stopped # always
    networks:
      - name: hoarder
    env:
      MEILI_NO_ANALYTICS=true
      MEILI_MASTER_KEY={{ hoarder.meili.master_key }}
    volumes:
      - /opt/hoarder/meili_data:/meili_data

- name: Docker - create container - hoarder
  docker_container:
    name: hoarder-web
    image: ghcr.io/hoarder-app/hoarder:release
    state: started
    recreate: yes
    restart_policy: unless-stopped # always
    networks:
      - name: hoarder
    published_ports:
      - "3001:3000"
    volumes:
      - /opt/hoarder/data:/data
    env:
      DATA_DIR=/data
      NEXTAUTH_SECRET={{ hoarder.nextauth_secret }}
      NEXTAUTH_URL={{ hoarder.host_url }}
      MEILI_ADDR=http://hoarder-meilisearch:7700
      MEILI_MASTER_KEY={{ hoarder.meili.master_key }}
      BROWSER_WEB_URL=http://hoarder-chrome:9222
```
