### DISCUSSION TITLE
Ollama support not working on Windows

### DISCUSSION THREAD

**Discussion by advait404** [karakeep-app/karakeep#1128] [Q&A] [answered]
### Describe the Bug

ollama is not activaed for any of the ai functionality

### Steps to Reproduce

1. got the hoarder docker compose and .env files.
2. install and run ollama windows app.
3. download ollama models. i can view all models at `http://127.0.0.1:11434/api/tags`
4. tried tag generation and summary with ai. neither works

docer compose file
```
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
volumes:
  meilisearch: null
  data: null
networks: {}
```

.env file
```
HOARDER_VERSION=release
NEXTAUTH_SECRET=super_random_string
MEILI_MASTER_KEY=another_random_string
NEXTAUTH_URL=http://localhost:3000

OLLAMA_BASE_URL=http://host.docker.internal:11434
INFERENCE_TEXT_MODEL=llava:latest
INFERENCE_IMAGE_MODEL=llava:latest
OLLAMA_KEEP_ALIVE=2m
```

### Expected Behaviour

indeally it should activate the ollama model and use it to generate tags and summaries.

### Screenshots or Additional Context

i see somewhere regarding network configurations, but am not sure if it's the issue.
"Use --network="host" in your docker run command, then 127.0.0.1 in your docker container will point to your docker host."

### Exact Hoarder Version

0.22.0

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem
