### DISCUSSION TITLE
Chrome exit code 133

### DISCUSSION THREAD

**Discussion by stefnats** [karakeep-app/karakeep#1381] [Q&A]
Hey there, sorry but AI helped a bit with this issue text, i hope you can forgive me :) 

As this error occurs with the Chromium bundled in the docker-compose file with Karakeep, i feel like this could be a place to request help.

We’re hitting an unresolvable SIGTRAP (exit code 133) when launching Headless Chrome on an ARM64 Oracle Always Free instance, due to a known Chromium PartitionAlloc vs. 64 KiB page size bug. Despite raising /dev/shm size, trying multiple image tags (up to :124), and adding typical Docker workarounds, Chrome still aborts with a breakpoint trap. Below is our environment, reproduction steps, full Strace snippet, and prior attempts. We welcome any community ideas or pointers.

## Environment

- Host: Oracle Linux Server 8.6 (UEK8), aarch64; Page size: 64 KiB
- Docker: Engine 26.1.3, Compose v2.27.0, Cgroup v1
- Chrome Image: gcr.io/zenika-hub/alpine-chrome:123 (and also tested :124)
- Memory: 24 GiB total, shm_size: 2g, mem_limit: 4g, ulimits.memlock=-1

## Reproduction

- Compose config uses only command: to pass flags to the built‑in ENTRYPOINT

- Running docker-compose up chrome immediately exits:

- chrome-1 exited with code 133

- Manual strace inside a debug image shows Chrome mapping its allocator then hitting SIGTRAP in PartitionAlloc.

Strace Excerpt

```
mmap(NULL, 19660800, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xfffeed980000
mmap(0xfffeec6c0000, 16777216, …|MAP_ANONYMOUS, -1, 0) = 0xfffeec6c0000
...
--- SIGTRAP {si_signo=SIGTRAP, si_code=TRAP_BRKPT, si_addr=0xaaabdd310b34} ---
+++ killed by SIGTRAP (core dumped) +++
```

This matches upstream reports where Chromium’s BlockAllocator intentionally traps on 64 KiB systems
issues.chromium.org

## Diagnosis

1. **PartitionAlloc Bug**: On Linux/ARM64 with 64 KiB OS page size, Chromium’s `PartitionRoot::Init()` intentionally triggers a `SIGTRAP`.  
   - Red Hat Bugzilla: [2166146](https://bugzilla.redhat.com/show_bug.cgi?id=2166146)  
2. **Upstream Discussion**:  
   - Chromium issue: [PartitionAlloc and 64 KiB pages](https://chromium-review.googlesource.com/c/chromium/src/+/3821285)  
3. **Kernel Workaround**: Switching to Oracle UEK7 (4 KiB pages) or a newer kernel (e.g., UEKR7‑5.15+) avoids the trap.  
4. **Chromium Fix Version**: Patched in Chromium **121.0.6167.139-2** and later; Alpine images ≥ 123 should include it, but testing on both `:123` and `:124` still SIGTRAP.  
5. **ENOMEM Angle**: Some reports tie the trap to failed huge `mmap` reservations, but our host has ample RAM and `vm.max_map_count` set high.  
6. **Docker Edge Cases**: Similar “exit code 133” on Apple Silicon is often emulation‑related, but here we’re on native ARM64.  

## What We’ve Tried

- `shm_size: 2g`, `mem_limit: 4g`, `ulimits.memlock=-1` & `cap_add: SYS_ADMIN`  
- Overriding `command:` vs. `CHROMIUM_FLAGS` env var  
- Custom seccomp profile + `cap_add: SYS_ADMIN`  
- Testing `seleniarm/standalone-chromium` (but no debug port)  
- Building a debug image with `strace` (see above snippet)  
- Switching to `alpine-chrome:124` tag  
- Confirming `chromium-browser --version` inside container reports ≥ 123  

All yield the same `SIGTRAP` at allocator initialization.

---

## Request for Help

1. **Has anyone** successfully run Headless Chromium on AArch64 Oracle UEK8 (64 KiB page size) without switching kernels?  
2. **Any Docker flags** or kernel parameters beyond `vm.max_map_count` and `memlock` to avoid the PartitionAlloc trap?  
3. Is there a **custom PartitionAlloc patch** or an existing workaround image?  
4. **Other ideas** on bypassing this trap (e.g., runtime flags, env vars)?

Thank you for any insights—or pointers to alternative images/builds that definitively include the fix!

---

TL;DR

Chrome crashes with error code 133 on ARM based Always-Free Instance on Oracle Cloud.

**Comment by DIGist** [comment]
I'm having the issue as well on a x86 host. It appears there is a open bug for the alpine-chrome container:
https://github.com/jlandure/alpine-chrome/issues/261

**Comment by stefnats** [comment]
Ah well that seems to match. He said he switched to selenium/standalone-chromium, but i also did that, but wasn't able to communicate on remote debugging port 9222, does anybody know how to configure that?

**Comment by MohamedBassem** [comment]
@stefnats I really appreciate the super detailed bug report and mentioning all the things you tried and didn't work. This is a high quality bug report here.
I don't think there's much I can help with if the issue is with the alpine container itself, but I can definitely help making the `selenium/standalone-chromium` container work. Can you share the compose file you used for `selenium/standalone-chromium`?

**Reply by stefnats** [reply]
Sure, thanks for the flowers :) 

```yaml
version: "3.8"
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - data:/data
    ports:
      - 3020:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: "..."

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
```

so mostly standard. I was also trying the `selenium/standalone-chromium` image which didn't crash, but it doesn't launch the debugging port on 9222, or at least i wasn't able to get it running. Maybe somebody on here knows it, as i had no success with that?
