### DISCUSSION TITLE
Using Browserless as headless browser

### DISCUSSION THREAD

**Discussion by vhsdream** [karakeep-app/karakeep#1394] [Ideas]
I've been using Browserless instead of Chromium as the headless browser in Karakeep for several weeks now, and I find that it works quite well, and the performance is good. 

Mind you, I'm running Karakeep in a Proxmox LXC, using kind of a hybrid setup between the Proxmox script and a modified karakeep-linux script in [my fork of this repo](https://github.com/vhsdream/karakeep/tree/browserless), so results may be different for those running via Docker (which I suspect is the majority of people). I wanted to try it because I don't like the kind of hacked-together feeling of running headless Chromium in Debian, with the journal output showing a bunch of errors (although it all works) and also the fact that if you want to run Karakeep in Ubuntu, the installer script has to add a third-party repo in order to get Chromium installed.

Is there anyone running via Docker who has tried using a Browserless container? If so, what are your results, and share how you've set it up (I guess you would do it through Docker Compose?).

And @MohamedBassem - I'm thinking of switching the karakeep-linux install script over to using Browserless for the next version. What do you think about this idea?

**Comment by a10kiloham** [comment]
here's the service from my compose.yml. works better for me than anything else! just need to find a way to add my cookies to it one day.

```
  karakeep_chrome:
    container_name: karakeep_chrome
    hostname: karakeep_chrome
    image: ghcr.io/browserless/chrome:latest
    networks:
      - hoardernet
    restart: always
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - TIMEOUT=600000 # Now 10 minutes
      - CONCURRENT=15
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:3000/active || exit 1
      interval: 40s
      timeout: 30s
      retries: 5
      start_period: 60s
```
