### DISCUSSION TITLE
Meilisearch database error, unable to login with newly created user.

### DISCUSSION THREAD

**Discussion by schumi2004** [karakeep-app/karakeep#1458] [Q&A]
### Describe the Bug

I don't get it.
When it was Hoarder i was also facing issues.
Gave it another shot now it is Karakeep but again i just can't get it working.

```
Error: Your database version (1.13.3) is incompatible with your current engine version (1.0.0).

To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
```

This is my compose which i think is valid?
I do have NEXT_AUTH_URL in env file as described in setup but it seems not being used?

```
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    container_name: web
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - data:/data
    ports:
      - 4000:3000
    env_file:
      - .env
    environment:
      #DISABLE_SIGNUPS: true
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
    networks:
      - proxy
    labels:
    # Traefik config
      - "traefik.enable=true"
      - "traefik.http.routers.karakeep.entrypoints=https"
      - "traefik.http.routers.karakeep.rule=Host(`karakeep.${DOMAINNAME_HS}`)"
      - "traefik.http.routers.karakeep.tls=true"
      - "traefik.http.routers.karakeep.service=karakeep"
      - "traefik.http.routers.karakeep.middlewares=internal@file"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - proxy

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
    networks:
      - proxy

volumes:
  meilisearch:
  data:

networks:
  proxy:
    external: true
```

### Steps to Reproduce

Followed install instructions and added Traefik config to it.
Navigated to localhost:4000 (port change since 3000 is already in use) and created user.
Unable to login.

Checked logs and noticed below error:
Meilisearch error:
Error: Your database version (1.13.3) is incompatible with your current engine version (1.0.0).

To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.

Chrome error:
[0523/151715.565860:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[0523/151715.565954:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[0523/151715.568160:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[0523/151715.633674:WARNING:sandbox_linux.cc(420)] InitializeSandbox() called with multiple threads in process gpu-process.

[0523/151715.759847:INFO:config_dir_policy_loader.cc(118)] Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed

[0523/151715.759881:INFO:config_dir_policy_loader.cc(118)] Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended

DevTools listening on ws://0.0.0.0:9222/devtools/browser/4dc6a365-f2b6-4315-b5dd-3067b33ca4da

[0523/151715.785381:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
### Expected Behaviour

To have a working environment when using the initial provided compose file

### Device Details

Docker

### Exact Karakeep Version

Latest

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem
