### DISCUSSION TITLE
Alternative port in docker compose

### DISCUSSION THREAD

**Discussion by zorel** [karakeep-app/karakeep#1548] [Q&A]
### Describe the Bug

I'd like to use an alternative port in docker-compose file. 3000 conflicts with Grafana.
```
  - 3300:3000
```
Doing that, the application is not accessible anymore.

```
curl -v 127.0.0.1:3300
*   Trying 127.0.0.1:3300...
* connect to 127.0.0.1 port 3300 from 127.0.0.1 port 54504 failed: No route to host
* Failed to connect to 127.0.0.1 port 3300 after 3100 ms: Could not connect to server
* closing connection #0
curl: (7) Failed to connect to 127.0.0.1 port 3300 after 3100 ms: Could not connect to server

```

I tried NEXTAUTH_URL to empty string, `http://127.0.0.1:3000` and `http://127.0.0.1:3300` with the same result.

I'm using podman-compose with podman 5.4.1

### Steps to Reproduce

1. Change the host port in docker compose file
2. podman-compose up
3. Try to access the app

### Expected Behaviour

/

### Device Details

Linux Ubuntu 25 with podman

### Exact Karakeep Version

0.24.1

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem

**Comment by MohamedBassem** [comment]
Hey, changing the port in the docker compose is the correct way of doing it. It's not clear to me why it didn't work for you, but that's the proper way of doing it and I think the problem you're facing might not be related to karakeep. Is port 3300 perhaps used by something else?

The error you're seeing probably indicate that the container didn't start successfully. can you share the logs of the container?

**Comment by zorel** [comment]
### I keep the overall thing for "history".

**- Using port 3100 does not work. I have the issues listed in this post. When I use 8081 instead, everything works fine. Go figure...**


Before:

```
# ss -lnt
State                             Recv-Q                            Send-Q                                                       Local Address:Port                                                        Peer Address:Port                            
LISTEN                            0                                 4096                                                               0.0.0.0:9130                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                               0.0.0.0:5678                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                               0.0.0.0:8086                                                             0.0.0.0:*                               
LISTEN                            0                                 1024                                                             10.89.0.1:53                                                               0.0.0.0:*                               
LISTEN                            0                                 4096                                                             127.0.0.1:8080                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                             127.0.0.1:631                                                              0.0.0.0:*                               
LISTEN                            0                                 4096                                                             127.0.0.1:53                                                               0.0.0.0:*                               
LISTEN                            0                                 4096                                                                 [::1]:631                                                                 [::]:*       

```

compose file 
```
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /opt/karakeep/data:/data
    ports:
      - 3100:3000
    env_file:
      - /opt/karakeep/environment
    environment:
      MEILI_ADDR: http://host.containers.internal:7700
      BROWSER_WEB_URL: http://host.containers.internal:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    ports:
      - 9222:9222
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    ports:
      - 7700:7700
    env_file:
      - /opt/karakeep/environment
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /opt/karakeep/meilisearch:/meili_data
```

Start with `podman-compose --file karakeep.yml up`.

After:
```
# ss -lnt
State                             Recv-Q                            Send-Q                                                       Local Address:Port                                                        Peer Address:Port                            
LISTEN                            0                                 4096                                                               0.0.0.0:9222                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                               0.0.0.0:9130                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                               0.0.0.0:5678                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                            127.0.0.53:8080                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                               0.0.0.0:8086                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                               0.0.0.0:7700                                                             0.0.0.0:*                               
LISTEN                            0                                 1024                                                             10.89.0.1:53                                                               0.0.0.0:*                               
LISTEN                            0                                 4096                                                            127.0.0.53:53                                                               0.0.0.0:*                               
LISTEN                            0                                 4096                                                               0.0.0.0:3100                                                             0.0.0.0:*                               
LISTEN                            0                                 4096                                                             127.0.0.1:631                                                              0.0.0.0:*                               
LISTEN                            0                                 4096                                                                 [::1]:631                                                                 [::]:* 
```

Tests:
```
# nc -vz localhost 3100
nc: connect to localhost (127.0.0.1) port 3100 (tcp) failed: No route to host
# curl http://127.0.0.1:3100
curl: (7) Failed to connect to 127.0.0.1 port 3100 after 3067 ms: Could not connect to server
```
