### DISCUSSION TITLE
karakeep-app/karakeep does not start

### DISCUSSION THREAD

**Discussion by BitNike** [karakeep-app/karakeep#1646] [Q&A]
### Describe the Bug

Hi, 
has recently stopped starting in the web container. 
The log files are:
```
0616/182911.436281:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
chrome-1       | [0616/182911.436331:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
web-1          | s6-rc: warning: unable to start service init-db-migration: command exited 1
chrome-1       | [0616/182911.498960:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
chrome-1       | 
chrome-1       | DevTools listening on ws://0.0.0.0:9222/devtools/browser/96ca98ce-432f-47b4-90a3-6e643ed14e73
chrome-1       | [0616/182911.523376:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
chrome-1       | [0616/182911.589777:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.

```

karakeep run very stable. 

I think Watchtower has made an update and since then there is this problem. 
Does anyone have this problem and a solution?

My Docker Compose Skript. 
```
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:latest #${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - data:/data
    ports:
      - 3111:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      INFERENZBILDMODELL: gpt-4o-mini
      INFERENCE_LANG: german
      DISABLE_SIGNUPS: true
      MAX_ASSET_SIZE_MB: 1024
      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
volumes:
  meilisearch: null
  data: null
networks: {}
```

### Steps to Reproduce

-

### Expected Behaviour

-

### Exact Karakeep Version

25.0

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem
