### DISCUSSION TITLE
Authelia OIDC Client Config - Hoarder OAUTH SSO

### DISCUSSION THREAD

**Discussion by tdharris** [karakeep-app/karakeep#419] [Show and tell]
In case it's ever helpful for someone, I thought I'd share a sample config for an **Authelia** [OIDC](https://docs.hoarder.app/configuration/#authentication--signup) Integration:

1. Authelia client config:
    ```yml
    - client_id: 'hoarder'
      client_name: 'Hoarder'
      client_secret: '<generated_plaintext_client_secret>'
      token_endpoint_auth_method: client_secret_basic
      authorization_policy: two_factor # optional
      redirect_uris:
        - 'https://<hoarder_address>/api/auth/callback/custom'
      audience: # optional
        - 'https://<hoarder_address>'
      grant_types: # optional
        - authorization_code
      scopes:
        - openid
        - profile
        - email
    ```

    - Based on various failed attempts, it seemed that `token_endpoint_auth_method: client_secret_basic` was necessary, with the `client_secret` configured with a plaintext value. For more information, see [How Do I Generate a Client Identifier or Client Secret](https://www.authelia.com/integration/openid-connect/frequently-asked-questions/#how-do-i-generate-a-client-identifier-or-client-secret).

2. Hoarder config:

    ```bash
    # .env
    OAUTH_WELLKNOWN_URL=https://<authelia_address>/.well-known/openid-configuration
    OAUTH_CLIENT_SECRET=<plaintext_client_secret_from_authelia>
    OAUTH_CLIENT_ID=hoarder
    OAUTH_PROVIDER_NAME=authelia
    NEXTAUTH_URL=https://<hoarder_address>
    ```

> [!NOTE]
> Please let me know if there are other known working configs that might be helpful.
