### DISCUSSION TITLE
Is there a way to disable the crawler requirement?

### DISCUSSION THREAD

**Discussion by rowanfuchs** [karakeep-app/karakeep#591] [General]
Is there a way to disable the crawler requirement?

**Comment by kamtschatka** [comment]
What do you consider the crawler requirement?
If you don't have a crawler, you will not get any crawling results, so basically you should only use it for text bookmarks then. The crawler is already not required?

**Comment by rowanfuchs** [comment]
text bookmarks is fine for me, the reason why I am asking is because the log fills up with the following lines:

```
2024-10-27T14:53:12.321Z info: Launching a new browser instance
2024-10-27T14:53:12.325Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
```

I've only launched the hoarder app to keep it as minimal as possible:

```
services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:latest
    container_name: hoarder
    restart: unless-stopped
    volumes:
      - /mnt/hdd/hoarder/config:/data
    ports:
      - 5030:3000
    environment:
      - DATA_DIR=/data
      - NEXTAUTH_SECRET=xxxxx
      - NEXTAUTH_URL=xxxx

```
