### ISSUE TITLE
"no such table: tasks" when adding a new bookmark

### ISSUE THREAD

**Issue by 3Andryu** [karakeep-app/karakeep#1226]
### Describe the Bug

First install. Here my Portainer stack:

```
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep
    restart: on-failure:5
    user: 1027:100
    volumes:
      - /volume1/***/karakeep/data:/data:rw
    ports:
      - 3022:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: ***
      MEILI_MASTER_KEY: ***
      NEXTAUTH_URL: http://localhost:3022

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: on-failure:5
    user: 1027:100
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: karakeep-meili
    restart: on-failure:5
    user: 1027:100
    volumes:
      - /volume1/***/karakeep/meilisearch:/meili_data:rw
    environment:
      HOARDER_VERSION: release
       NEXTAUTH_SECRET: ***
       MEILI_MASTER_KEY: ***
       NEXTAUTH_URL: http://localhost:3022
      MEILI_NO_ANALYTICS: true
```

karakeep web container log:

```
Error: EACCES: permission denied, mkdir '/.cache/node/corepack/v1'

    at mkdirSync (node:fs:1364:26)

    at getTemporaryFolder (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21493:27)

    at download (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21767:21)

    at installVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21861:61)

    at async Engine.ensurePackageManager (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22323:32)

    at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22423:25)

    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23110:7) {

  errno: -13,

  code: 'EACCES',

  syscall: 'mkdir',

  path: '/.cache/node/corepack/v1'

}

Node.js v22.14.0
```

### Steps to Reproduce

Add new bookmark

### Expected Behaviour

No message: "no such table: tasks" 

### Exact Hoarder Version

release

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem
