### ISSUE TITLE
Upgraded from Hoarder 0.23.0 to Karakeep 0.23.2. What else should I do?

### ISSUE THREAD

**Issue by mihha** [karakeep-app/karakeep#1234]
Hi,

I had Hoarder 0.23.0 installed and I just did the following:

```
docker compose stop
docker compose pull
docker compose up -d
```

I see that now I have Karakeep 0.23.2 

Is there anything else I need to do?

I didn't change anything in my docker-compose file so it still lokks like this:

```
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 5000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meilisearch:/meili_data
```
