### ISSUE TITLE
Karakeep API Keys unusable

### ISSUE THREAD

**Issue by Rek-Malorm** [karakeep-app/karakeep#1377]
### Describe the Bug

When trying to use any api key with MCP or cli tool, the response is `Error: Unable to fetch information about the owner of this API key. Reason: UNAUTHORIZED`

### Steps to Reproduce

Open UI
Create new API Key

Using Karakeep-cli

`karakeep --api-key **_redacted_** --server-addr https://redacted.arpa whoami`

Result:

Error: `Unable to fetch information about the owner of this API key. Reason: UNAUTHORIZED`

Same error when using mcp

The documentation is not clear on how auth works.

My compose file is as follows

```

services:
  meilisearch:
    image: getmeili/meilisearch:v1.9.0
    container_name: meilisearch
    networks:
      br1_network: {}
      karakeep_net: {}
    deploy:
      resources:
        limits:
          pids: 2048
    environment:
      - TCP_PORT_7700=7700
      - MEILI_MASTER_KEY=<REDACTED>
      - FORCE_DEPLOY=true
      - MEILI_NO_ANALYTICS=false
      - MEILI_ENV=production
    labels:
      folder.view: "Karakeep"
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: https://raw.githubusercontent.com/Collectathon/unraid-templates/main/icons/meilisearch.png
    volumes:
      - /mnt/user/appdata/meilisearch:/meili_data:rw
    restart: unless-stopped

  browserless:
    image: browserless/chrome
    container_name: browserless
    networks:
      br1_network: {}
      karakeep_net: {}
    deploy:
      resources:
        limits:
          pids: 2048
    environment:
      - TCP_PORT_3000=3000
      - BROWSER_WEBSOCKET_URL=ws://192.168.10.23:3000?token=
    labels:
      folder.view: "Karakeep"
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3000]
      net.unraid.docker.icon: https://raw.githubusercontent.com/Collectathon/unraid-templates/main/icons/browserless.png
    restart: unless-stopped

  karakeep:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep
    networks:
      br0_network:
        ipv4_address: 192.168.10.22
      karakeep_net: 
        ipv4_address: 172.30.40.10
    deploy:
      resources:
        limits:
          pids: 2048
    environment:
      - TCP_PORT_3000=3000
      - NEXTAUTH_URL=<REDACTED>
      - NEXTAUTH_SECRET=<REDACTED>
      - BROWSER_WEBSOCKET_URL=ws://browserless:3000?token=
      - MEILI_ADDR=http://meilisearch:7700
      - MEILI_MASTER_KEY=<REDACTED>
      - DISABLE_SIGNUPS=false
      - OLLAMA_BASE_URL=<REDACTED>
      - INFERENCE_TEXT_MODEL=gemma3:latest
      - INFERENCE_IMAGE_MODEL=llava
      - DATA_DIR=/data
      - BROWSER_CONNECT_ONDEMAND=true
    labels:
      folder.view: "Karakeep"
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: <REDACTED>
      net.unraid.docker.icon: https://raw.githubusercontent.com/Collectathon/unraid-templates/main/icons/hoarder.png
    volumes:
      - /mnt/user/appdata/hoarder:/data:rw
    restart: unless-stopped

networks:
  br0_network:
    name: br0
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
  br1_network:
    name: br1
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1

  karakeep_net:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.30.40.0/24
          gateway: 172.30.40.1
```

### Expected Behaviour

Api returns the result of the request

### Device Details

Arch Linux

### Exact Karakeep Version

0.24.1

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem
