### ISSUE TITLE
Page is too large error on specific pages.

### ISSUE THREAD

**Issue by Ardakilic** [karakeep-app/karakeep#1469]
Hello,

I'm trying to capture some screenshots to a webpage.

https://www.audioreviews.org/guide-to-iem-silicone-eartips/

When I try to fetch, I get this in the logs.

```
karakeep-web  | 2025-05-25T12:04:30.404Z warn: [Crawler][88] Failed to capture the screenshot. Reason: ProtocolError: Protocol error (Page.captureScreenshot): Page is too large.
```

These are in my environment:

```
CRAWLER_FULL_PAGE_SCREENSHOT: "true"
CRAWLER_SCREENSHOT_TIMEOUT_SEC: 120
```

But this happens even before waiting for 120 secs.

I simply want the full page screenshot.

I'm running from Docker, and this is roughly my configuration:

```
# Karakeep
  karakeep-web:
    container_name: karakeep-web
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      - ./karakeep/data:/data
    # ports:
    #   - 8911:3000
    environment:
      MEILI_ADDR: http://karakeep-meilisearch:7700
      BROWSER_WEB_URL: http://karakeep-chrome:9222
      # OPENAI_API_KEY: ...
      NEXTAUTH_SECRET: Nope
      MEILI_MASTER_KEY: Nope2
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
      # APP CONFIGURATION
      DISABLE_SIGNUPS: "true" # set to true to disable signups
      CRAWLER_FULL_PAGE_SCREENSHOT: "true"
      CRAWLER_SCREENSHOT_TIMEOUT_SEC: 120
      OLLAMA_BASE_URL: http://host.docker.internal:11434 # ollama is installed locally
      INFERENCE_TEXT_MODEL: gemma3:12b
      INFERENCE_IMAGE_MODEL: minicpm-v:latest
  karakeep-chrome:
    container_name: karakeep-chrome
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  karakeep-meilisearch:
    container_name: karakeep-meilisearch
    image: getmeili/meilisearch:v1.14.0
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: Nope2
    volumes:
      - ./karakeep/meilisearch:/meili_data
  # Karakeep end
```

I'm also using [Docker Swag](https://github.com/linuxserver/docker-swag/) for nginx reverse proxy and it's been working nicely for me for years, but I believe this is unrelated, but wanted to mention nevertheless.

This works nicely with Ollama and stuff, only except the page screenshot is giving me issue.

I checked the [configuration](https://docs.karakeep.app/configuration), but I could not find anything helpful regarding this.

I'd appreciate if you could help me, what am I missing?

Thanks in advance!
