### ISSUE TITLE
OAuth login failed: No profile

### ISSUE THREAD

**Issue by chain710** [karakeep-app/karakeep#410]
![image](https://github.com/user-attachments/assets/12d37683-0827-4607-9c3b-b93db076449d)

My oauth provider: authelia 4.38.12

- click `Sign in with authelia` redirect to authelia sso page
- click `accept` redirect back to hoarder login page, but got error `OAuth login failed: No profile`

my authelia instance works well with other self-host services like linkwarden and immich

found no useful log via `docker logs hoarder`

```
....

2024-09-23T14:47:13.944Z info: Workers version: 0.17.0
2024-09-23T14:47:13.954Z info: [Crawler] Connecting to existing browser instance: http://chrome:9222
(node:121) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2024-09-23T14:47:13.960Z info: [Crawler] Successfully resolved IP address, new address: http://172.20.0.29:9222/
2024-09-23T14:47:15.981Z info: Starting crawler worker ...
2024-09-23T14:47:15.981Z info: Starting inference worker ...
2024-09-23T14:47:15.981Z info: Starting search indexing worker ...
```

env 

```
REDIS_HOST=redis
REDIS_DB_IDX=15
DATA_DIR=/data
NEXTAUTH_SECRET=secret
BROWSER_WEB_URL=http://chrome:9222
MEILI_ADDR=http://meilisearch:7700
MEILI_NO_ANALYTICS=true
MEILI_MASTER_KEY=key
OPENAI_API_KEY=key
INFERENCE_IMAGE_MODEL=gpt-4o-mini
INFERENCE_TEXT_MODEL=gpt-4o-mini
OAUTH_WELLKNOWN_URL=https://auth.example.com/.well-known/openid-configuration
OAUTH_CLIENT_SECRET=secret
OAUTH_CLIENT_ID=hoarder
OAUTH_PROVIDER_NAME=authelia
NEXTAUTH_URL=https://h.example.com
```

**Comment by kamtschatka** [comment]
this happens, when authelia does not provide an email address or a name for the user you are using: https://github.com/hoarder-app/hoarder/blob/main/apps/web/server/auth.ts#L150

you'll have to check on authelia side to fill those in.

**Comment by MohamedBassem** [comment]
@kamtschatka I think we should probably remove the name restriction. If it's empty, we can just use the email and not fail the login on it.

**Comment by mirisbowring** [comment]
Hi, I just tried to install hoarder today and wanted to connect it to my authentik install.
I experience the same behavior like OP.

I first tried `release` (which points to 17.1) and also `latest` but none of them fixed the issue.

Side Note: all fields in my OIDC Profile are set. There is a name, a username, an email, etc. so in theory this should work independent of the fix from above, no? :)

Thank you very much!

**Comment by MohamedBassem** [comment]
@mirisbowring what kind of error did you get? `No profile` as well?

**Comment by mirisbowring** [comment]
Yep: 
<img width="391" alt="image" src="https://github.com/user-attachments/assets/970a8cd7-60cd-4a4f-bfce-f8e35d5e628a">

**Comment by MohamedBassem** [comment]
@mirisbowring yeah, that's weird indeed. Did you by any chance change the `OAUTH_SCOPE` value?

**Comment by mirisbowring** [comment]
I've just set it to the defaults:

```yaml
OAUTH_SCOPE="openid email profile"
```

**Comment by mirisbowring** [comment]
![image](https://github.com/user-attachments/assets/331950f8-98a2-4158-8510-129bd4c09850)
I also checked the available fields resulting from `https://auth.domain.tld/application/o/userinfo/`

**Comment by mirisbowring** [comment]
Hi, since this issue persists, can we reopen this issue?

**Comment by eapetitfils** [comment]
I am getting the same issue on a fresh install of hoarder using authentik (link for configuration here: https://docs.goauthentik.io/integrations/services/hoarder/).

I can confirm in the logs of authentik that the email is part of the response. I tried with the username having no existing native account in hoarder, and with an existing one, also with various configurations of  OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING

`{
    "pk": 7,
    "email": "correct email",
    "username": "correct username"
}`

**Comment by flavienbwk** [comment]
For Keycloak, I just had to have emails set for my users.

**Comment by 0dragosh** [comment]
I still have this issue, can we reopen?

**Comment by petrm** [comment]
I upgraded authelia to 4.39 and this issue appeared. Never had it before. Hoarder config in authelia allows openid profile groups email, exactly like before. Other applications don't seem to have this problem.

**Comment by 0dragosh** [comment]
Also had this problem with authelia 4.39. This is the [issue](https://github.com/authelia/authelia/issues/8979). Authelia 4.39.1 is now out which fixes it.

**Comment by petrm** [comment]
I still see it with 4.39.1.

**Comment by petrm** [comment]
I figured it out. There are clearly different reasons for this issue to appear. In my case, it is caused by changes introduced in 4.39: https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter
The authelia docs have recommendation what to implement in the client or in the link above, a workaround.

**Comment by subract** [comment]
Thank you @petrm! I implemented the linked workaround successfully after being unable to get Hoarder and Authelia to play nice for weeks now. 

I agree that this issue should be reopened to track implementing the proper fix from the linked article:

> We strongly recommend implementers use the standard process for obtaining the extra claims not generally intended to be included in the [ID Token](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) by using the [Access Token](https://datatracker.ietf.org/doc/html/rfc6749#section-1.4) to obtain them from the [UserInfo Endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo).

**Comment by scottharney** [comment]
Wanted to confirm same with authelia.  I was able to apply the linked workaround to restore the legacy claims_poicy functionaliy in the authelia configuration and that allowed hoarder to work with  authelia 4.39.1.

**Comment by kobusestas** [comment]
@petrm @scottharney @subract How did you get this working in Authelia? I added this to my Authelia Config:
```
identity_providers:
  oidc:
    claims_policies:
      ## Creates the 'default' claims policy.
      default:
        id_token: ['rat', 'groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
```
and then in the "- Client_ID" section I added
`        claims_policy: 'default'`

However I still see this error. Any chance you could help point me in the right direction to see what I'm missing?

I'm using cloudflare for DNS proxy if that matters at all. This was working previously.

**Comment by scottharney** [comment]
I followed the link in petrm's comment above mine to authelia docs for the workaround to restore the previous functionality for the claims parameter https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter
I made the edits described there to my authelia configuration and restarted and the integration with hoarder worked again

**Comment by petrm** [comment]
@kobusestas 
Looks like my config, except I don't have 'rat' in the list.

**Comment by cything** [comment]
You don't have to enable all of those claims. According to the logic [here](https://github.com/karakeep-app/karakeep/blob/27324a963120fe7a6aeff7cfbe358db5b3fafe7a/apps/web/server/auth.ts#L159), only `email` is needed. This is what my config looks like and it works:
```yaml
identity_providers:
  oidc:
    claims_policies:
      karakeep:
        id_token:
        - email
    clients:
    - client_name: Karakeep
      claims_policy: karakeep
```

**Comment by Eragos** [comment]
Authela worked for me version _v4.39.1_

Authelia config part:
```
      - client_id: 'karakeep'
        client_name: 'karakeep'
        client_secret: '$argon2id$v=...
        public: false
        token_endpoint_auth_method: 'client_secret_basic'
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://karakeep.domain.com/api/auth/callback/custom'
        audience:
          - 'https://karakeep.domain.com'
        requested_audience_mode: explicit
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
```

No special claim policy (default authelia/OICD).

And karakeep docker compose part:
```
[...]
    environment:
      - DISABLE_PASSWORD_AUTH=true
      - DISABLE_SIGNUPS=true
      - OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING=true
      - OAUTH_CLIENT_ID=karakeep
      - OAUTH_CLIENT_SECRET=<insecure secret>
      - OAUTH_PROVIDER_NAME=Authelia
      - OAUTH_SCOPE=openid email profile
      - OAUTH_WELLKNOWN_URL=https://auth.domain.com/.well-known/openid-configuration
[...]
```

Best Michael
