### ISSUE TITLE
Add user: "${UID}:${GID}" in compose.yaml

### ISSUE THREAD

**Issue by Ronaldvr** [karakeep-app/karakeep#606]
### Describe the feature you'd like

When experimenting with hoarder I found that deleting documents in the mounted directories was impossible without root access. This means the images are mounted with the root (1000) user. A simple solution is using the 
user: "${UID}:${GID}" 
in the yaml and adding those variables to the .env file
As explained for instance her: https://stackoverflow.com/questions/40462189/docker-compose-set-user-and-group-on-mounted-volume

### Describe the benefits this would bring to existing Hoarder users

Not only is this strongly recommended behaviour these days https://www.howtogeek.com/devops/why-processes-in-docker-containers-shouldnt-run-as-root/ it is easier and safer.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by kapsh** [comment]
I've been able to run every service defined in project's example compose from non-root user, e.g. `apps` with uid/gid `568`.

This requires managing data volumes manually, so first create base directory `${APPS_DATASET}/karakeep` writeable for user `apps` where `APPS_DATASET` is some absolute path of your choice. Subdirectories `data`, `cache` and `search` inside it will be used instead of named volumes, which is usually better idea for precious data than docker magic anyway. 
Next, mount subdirectories: `data` at default `/data` for karakeep itself, `search` at `/melli_search` (also their defaults) and `cache` shared for other things. 
To actually use `/cache` configure it's path in environment variables: 
- `COREPACK_HOME` - most important. Without this karakeep cannot start, because corepack tries to download pnpm into `/.cache` in rootfs.
- `HOME` for chrome service. It will cache fonts and certificates in there and maybe could work without setting, just shows warning on launch.

With this configuration karakeep runs, saves links, their screenshots and archives, OCR, tags and search work, etc. Resulting compose (only settings relevant to topic):
```yaml
services:

  karakeep:
    image: ghcr.io/karakeep-app/karakeep:0.23.1
    volumes:
      - ${APPS_DATASET}/karakeep/data:/data
      - ${APPS_DATASET}/karakeep/cache:/cache
    environment:
      DATA_DIR: /data
      COREPACK_HOME: /cache/corepack
      OCR_CACHE_DIR: /cache/ocr
    user: "568:568"

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    environment:
      HOME: /cache/chrome
    volumes:
      - ${APPS_DATASET}/karakeep/cache:/cache
    user: "568:568"

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    volumes:
      - ${APPS_DATASET}/karakeep/search:/meili_data
    user: "568:568"
```

There are some partially solved issues, like this error in logs when browsing or probably creating previews:
```
 ⨯ Failed to write image to cache Wieiqxxj-xhnpz2SHeXAUqn0CRer6gg1yVUlctnBFO0= Error: EACCES: permission denied, mkdir '/app/apps/web/.next/cache'
    at async Object.mkdir (node:internal/fs/promises:857:10)
    at async writeToCacheDir (/app/node_modules/next/dist/server/image-optimizer.js:178:5)
    at async ImageOptimizerCache.set (/app/node_modules/next/dist/server/image-optimizer.js:451:13)
    at async /app/node_modules/next/dist/server/response-cache/index.js:121:25
    at async /app/node_modules/next/dist/lib/batcher.js:45:32 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/app/apps/web/.next/cache'
}
```
Sound like Next.js data cache, I couldn't find how to configure it's location. Doesn't break anything visible, but to be safe this path can be hacked with some post-deploy command like `docker compose exec -u0 karakeep install -d -o 568 /app/apps/web/.next/cache` which runs _from root_ to create writable for user 568 directory inside running container.
